server:
  port: 6001
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#        https://github.com/diaoyuhang/online-taxi-config-server.git
          uri: https://github.com/diaoyuhang/online-taxi-config-server
          username: 
          password: 
          #默认单位秒，因为git慢
          timeout: 20
    
#注册中心
eureka: 
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@localhost:7900/eureka/
  instance: 
    instance-id: config-server
